// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Resource struct {
	User     uint64
	Path     string
	Hidden   bool
	Starred  bool
	ViewTime sql.NullTime
	ReadTime sql.NullTime
}

type User struct {
	ID           uint64
	Name         string
	PasswordHash []byte
}
