// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM users
WHERE id = ?
`

// DeleteUser removes a user and their resources from the system.
func (q *Queries) DeleteUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT user, path, hidden, starred, view_time, read_time
FROM resources
WHERE user = ?
  AND path = ?
LIMIT 1
`

type GetResourceParams struct {
	User uint64
	Path string
}

// GetResource returns a resource matching the specified user and path.
func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, arg.User, arg.Path)
	var i Resource
	err := row.Scan(
		&i.User,
		&i.Path,
		&i.Hidden,
		&i.Starred,
		&i.ViewTime,
		&i.ReadTime,
	)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT user, path, hidden, starred, view_time, read_time
FROM resources
WHERE user = ?
  AND path in (/*SLICE:paths*/?)
`

type GetResourcesParams struct {
	User  uint64
	Paths []string
}

// GetResources returns all resources matching the specified user and one of the paths.
func (q *Queries) GetResources(ctx context.Context, arg GetResourcesParams) ([]Resource, error) {
	query := getResources
	var queryParams []interface{}
	queryParams = append(queryParams, arg.User)
	if len(arg.Paths) > 0 {
		for _, v := range arg.Paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(arg.Paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.User,
			&i.Path,
			&i.Hidden,
			&i.Starred,
			&i.ViewTime,
			&i.ReadTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, password_hash
FROM users
WHERE id = ?
LIMIT 1
`

// GetUser fetches a user by ID.
func (q *Queries) GetUser(ctx context.Context, id uint64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password_hash
FROM users
WHERE name = ?
LIMIT 1
`

// GetUserByName fetches a user by their name.
func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, password_hash
FROM users
WHERE name > ?2
ORDER BY name
LIMIT ?1
`

type GetUsersParams struct {
	Limit     int64
	AfterName string
}

// GetUsers fetches a list of users starting after the provided name.
func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Limit, arg.AfterName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.PasswordHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserName = `-- name: SetUserName :one
UPDATE users
SET name = ?2
WHERE id = ?1
RETURNING id, name, password_hash
`

type SetUserNameParams struct {
	ID   uint64
	Name string
}

// SetUserName updates a user's name with the given ID.
func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserName, arg.ID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :one
UPDATE users
SET password_hash = ?2
WHERE id = ?1
RETURNING id, name, password_hash
`

type SetUserPasswordHashParams struct {
	ID           uint64
	PasswordHash []byte
}

// SetUserPasswordHash updates a user's password hash with the given ID.
func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const upsertResource = `-- name: UpsertResource :one
INSERT INTO resources (user, path, hidden, starred, view_time, read_time)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT DO UPDATE SET hidden    = ?3,
                          starred   = ?4,
                          view_time = ?5,
                          read_time = ?6
WHERE user = ?1
  AND path = ?2
RETURNING user, path, hidden, starred, view_time, read_time
`

type UpsertResourceParams struct {
	User     uint64
	Path     string
	Hidden   bool
	Starred  bool
	ViewTime sql.NullTime
	ReadTime sql.NullTime
}

// UpsertResource upserts a resource.
func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, upsertResource,
		arg.User,
		arg.Path,
		arg.Hidden,
		arg.Starred,
		arg.ViewTime,
		arg.ReadTime,
	)
	var i Resource
	err := row.Scan(
		&i.User,
		&i.Path,
		&i.Hidden,
		&i.Starred,
		&i.ViewTime,
		&i.ReadTime,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, name, password_hash)
VALUES (?1, ?2, ?3)
ON CONFLICT DO UPDATE SET name          = ?2,
                          password_hash = ?3
WHERE id = ?1
RETURNING id, name, password_hash
`

type UpsertUserParams struct {
	ID           uint64
	Name         string
	PasswordHash []byte
}

// UpsertUser adds a new user with the given name and password_hash.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.ID, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}
